### ISSUE TITLE
range_check

### ISSUE THREAD

**Issue by ClementWalter** [ClementWalter/cairo-vm-gs#16]
# Why

Some segments called built-ins enforces special behaviors in between their cells.

For built-ins in this implementation, we are going to write functions that implement the logic and set them as formula in the right cells.

The range_check bultins only assert that values are `< RC_BOUND` which is actually `2**128`.

# What

- [ ] create a `builtins.ts` file
- [ ] implement a `RANGE_CHECK` function that return the value if < 2**128 and raises otherwise
- [ ] in the `vm.step()` method, when writing in the `range_check` segment, set formula as `RANGE_CHECK(value)` instead of `value` only.

**Comment by KeneePatel** [comment]
I would be happy to take on this issue.
