### ISSUE TITLE
feat: add pedersen built-in

### ISSUE THREAD

**Issue by ClementWalter** [ClementWalter/cairo-vm-gs#17]
See also
See also https://docs.cairo-lang.org/how_cairo_works/builtins.html
https://github.com/starkware-libs/cairo-lang/blob/master/src/starkware/cairo/common/hash.cairo

- [ ] find or do a js implementation of the pedersen hash function
- [ ] add a `PEDERSEN(x, y)` function calling it

**Comment by AntoineFONDEUR** [comment]
Hey can I work on this issue ?
