### ISSUE TITLE
Migrate to Typescript

### ISSUE THREAD

**Issue by ClementWalter** [ClementWalter/cairo-vm-gs#2]
# Why

The project currently uses vanilla js. It would be better (easier to maintain, to understand) to use typescript.

# What

Rewrite all the codebase in typescript

# How

1. Follow [the doc](https://github.com/google/clasp/blob/master/docs/typescript.md) to use ts in google app scripts
2. Create a `types.ts` file gathering all the types
3. Refactor codebase to use ts

**Comment by uttamsah724** [comment]
I have good work on typescript, can I go for it? @ClementWalter

**Comment by Joy-Adah** [comment]
Can I be assigned to this @ClementWalter

**Comment by ClementWalter** [comment]
hey @Joy-Adah @jaipaljadeja let's wait for the other issues to complete to avoid too many conflicts!

**Comment by KeneePatel** [comment]
Hey there, Would love to work on this issue.

**Comment by KeneePatel** [comment]
Hey Again! I kinda started working on it. Please check out https://github.com/KeneePatel/cairo-vm-gs/tree/ts-migration and let me know if the changes are fine and if it is merge-ready.

**Comment by ClementWalter** [comment]
@KeneePatel well if od done then open a pr, will review from then
