### ISSUE TITLE
feat: add a a test framework

### ISSUE THREAD

**Issue by ClementWalter** [ClementWalter/cairo-vm-gs#23]
# Why

As the project gets bigger, we need tests

# What

Investigate google app scripts tests as well as the addition of a regular ts test framework for unit tests not depending on the sheet

See also:
https://stackoverflow.com/questions/15682346/how-to-unit-test-google-apps-scripts
https://jestjs.io/docs/getting-started

**Comment by AntoineFONDEUR** [comment]
can i get this one ?
