### ISSUE TITLE
feat: upon loading a program, initialize the Run tab

### ISSUE THREAD

**Issue by ClementWalter** [ClementWalter/cairo-vm-gs#25]
# Why

The VM is initialized based on a given program. So when using the UX to load a program, one also needs to update the initial state of the VM so that one can then `Run`.

# What

- [ ] Get the builtins from the file and initialize these builtins only
- [ ] initialize the stack

**Comment by saimeunt** [comment]
Hey I'd like to try this one 👍

**Comment by ClementWalter** [comment]
@saimeunt I'm sorry but I need to reassign the issue since you've not been able to work on it for a month
