### ISSUE TITLE
ecdsa

### ISSUE THREAD

**Issue by ClementWalter** [ClementWalter/cairo-vm-gs#28]
The `ecdsa` builtin is a `SignatureBuiltin`, see for example https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/common/signature.cairo#L10

**Comment by AntoineFONDEUR** [comment]
Hey I can implement a sign_message(message, private_key) function and a verify_signature(signature, message, public_key) function and add/modify the elliptic curve operations (add & multiply by integer).
