### ISSUE TITLE
feat: add initializeSegments method logic

### ISSUE THREAD

**Issue by ClementWalter** [ClementWalter/cairo-vm-gs#3]
# Why

The Cairo VM uses memory segments to track values. In short and almost true, a memory segment is just a list of values, ie. here a list of `felt` (`felt` is the only native type of cairo, think of `felt` as `uint252`).

A run of the VM actually consists in filling values in memory segments; allocating a segment just means creating an empty list at index _i_ in the segments manager of the VM, much like

```javascript
{
    0: [],
    1: [],
    42: [],
}
```

could be a memory with 3 initialized segments (with indexes 0, 1 and 42).

Segments can be allocated during the run (when the dev uses the `alloc()` function) or by the VM itself at the beginning of a run for given builtins. In cairo0, these builtins are declared at the tile level using the `% builtin` directive, and at the function level using corresponding implicit arguments.

The list of builtins actually available is:

```json
[
  "output",
  "pedersen",
  "range_check",
  "ecdsa",
  "bitwise",
  "ec_op",
  "keccak",
  "poseidon",
]
```

Each builtin requires its own memory segment as these builtins actually enforces some rules over the segment. For example, the `range_check` segment will enforce that every values contained in this segment are actually no greater than `2**128`.

Consequently, when initializing the VM for running a program, one needs to create as much memory segments as required.

# What

The Cairo VM gs uses native sheet columns as memory segments.
The function should add the corresponding column with their header as names next to the `Execution` column

# How

Follow the python VM https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/lang/vm/cairo_runner.py#L216
Note that program_base is always the first segment, and Execution the second.

Add a menu in the UI to actually trigger the call

The CairoVM will for now only run the main entrypoint, so the final fp and pc segments should be added last, and their reference be added in the execution segment.

**Comment by jaipaljadeja** [comment]
i am going through it. would like to give it a shot? can you assign me this?

**Comment by KeneePatel** [comment]
Hey @jaipaljadeja, I went through this issue and found it to be doable. If you are not working on this, can I pick this up?

**Comment by jaipaljadeja** [comment]
@ClementWalter can you assign this to kenny please?

**Comment by KeneePatel** [comment]
Thank you jaipaal. Appreciate it!

**Comment by ClementWalter** [comment]
@KeneePatel it's yours now
