### ISSUE TITLE
feat: fix all snake_case to use camelCase everywhere

### ISSUE THREAD

**Issue by ClementWalter** [ClementWalter/cairo-vm-gs#36]
I'm quite surprised that trunk doesn't catch this but let's use `camelCase` everywhere.

This issue is about fixing all the cases using `snake_case`

**Comment by AntoineFONDEUR** [comment]
Hey ! Can I take this one ?

**Comment by devcollinss** [comment]
Hello @ClementWalter, My name is Collins. I'd be interested in taking it on. I can deliver it as soon as possible.

**Comment by ClementWalter** [comment]
@devcollinss assigning @AntoineFONDEUR as he was the first to comment sorry, I was myself afk for few days
