### ISSUE TITLE
feat: add validation logic to step

### ISSUE THREAD

**Issue by ClementWalter** [ClementWalter/cairo-vm-gs#6]
# Why

Currently, the VM logic optimistically fills the memory to fit the res logic and opcode. There is however no check that the operation is legit. For example, an `assert 0 = 1` would just lead to a memory written to 0, then overridden to 1.

# What

Raise in `step` when the operation is not possible

# How

See https://github.com/starkware-libs/cairo-lang/blob/efa9648f57568aad8f8a13fbf027d2de7c63c2c0/src/starkware/cairo/lang/vm/vm_core.py#L386

**Comment by Joy-Adah** [comment]
I'd love to work on this @ClementWalter

**Comment by uttamsah724** [comment]
Can I implement this logic and build this feature?

**Comment by KeneePatel** [comment]
Hey @ClementWalter, Can I work on this?

**Comment by AntoineFONDEUR** [comment]
Hi can I take this one ?
