### ISSUE TITLE
feat: add a simple python cairo0 project

### ISSUE THREAD

**Issue by ClementWalter** [ClementWalter/cairo-vm-gs#7]
# Why

The cairo VM runs cairo wasm, and cairo0 is very close to it.

# What

- Create a python-poetry project
- add cairo-lang package
- create a simple hello_world.cairo

# How

-  check https://python-poetry.org/
- `poetry init`
- `poetry add cairo-lang`

Create a `fibonacci.cairo`, fill with a simple function like this one https://github.com/ClementWalter/hello-starknet/blob/main/src/jump.cairo, build and commit

**Comment by muheebyusufbaba1** [comment]
I'll like to do this

**Comment by JimmyFate** [comment]
I'll give it a go :)

**Comment by ClementWalter** [comment]
I guess that @JimmyFate was the first on the tg chat, sorry @muheebyusufbaba1 !

**Comment by muheebyusufbaba1** [comment]
Buh I commented on the repo first!

**Comment by ClementWalter** [comment]
@muheebyusufbaba1 we'll find you others!

**Comment by muheebyusufbaba1** [comment]
Alright will be glad
